// <auto-generated />
namespace API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class nasza_pierwsza_migracja : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nasza_pierwsza_migracja));
        
        string IMigrationMetadata.Id
        {
            get { return "202204051212365_nasza_pierwsza_migracja"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
